{"uuid": "a5d658be-35c6-4972-8aac-a56f6243cf21", "children": ["85447e4d-d3f7-4b80-bea7-813fea0615c2", "4d2f7918-14b5-4f63-9e21-2ff47473cd1f", "3108cdd8-7f2b-4ac6-bf02-17095c084d22", "07122a3f-da8b-4f82-a496-03cabdfb5314", "4b4f4f4d-ddc2-4691-8f1d-e0a510e7acf9", "28a9f3fb-ad66-4f7d-a9bd-9c1f318ee522", "d2925081-db3e-408b-b376-28273d259fcc", "ad9bb1a6-7e16-4fc2-b988-29f4f7d484f0", "1fbc1638-dc1b-4f48-bd99-e9931499a404"], "befores": [{"name": "supervisor_chain", "status": "broken", "statusDetails": {"message": "KeyError: 'llama3.2'\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/OA/OA/tests/supervisor_chain.py\", line 19, in supervisor_chain\n    llm = get_available_providers()[model]\n          ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^\n"}, "start": 1730427806838, "stop": 1730427807286}], "start": 1730427806838, "stop": 1730427808045}